### ISSUE TITLE
[FEATURE] Stripe Paywall integration with Login form

### ISSUE THREAD

**Issue by HerbstGewinn** [SiddhantSadangi/st_login_form#12]
I have used St-paywall in the first that uses GoogleOAuth in Conection with Stripe to login the user. 

It would be perfect, if there would be such a solution for the login form. So that the user logs in --> Information saved in the database --> Redirected to Stripe --> After payment, full usage of the app possible.

Thank you ! :)

**Comment by SiddhantSadangi** [comment]
Hey @HerbstGewinn 👋 

Since this is a very specific use case, adding such behavior to the library might be difficult.

The best option would be to use the supabase client returned by the login form to log any downstream metadata to supabase. Since the login form handles authentication by setting the `authenticated` session state to true, you can call st-paywall once the user has been authenticated and let it gatekeep your app. 

Does this sound like something that might work?
